# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categoryid',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='大类'),
        ),
    ]
